ICE-10908 Replaced SynchronizationMonitorObject instances with String object instances to avoid NoClassDefFoundError errors when application was removed from the file system and the web context was not yet fully disposed.